import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}> {/* Removed curly braces for better readability */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Vercel Trick By <a href="https://alcashzone.com">Alcash Zone</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          {/* ... Rest of your code remains the same ... */}
        </div>
      </main>

      <footer className={styles.footer}>
        {/* ... Rest of your code remains the same ... */}
      </footer>
    </div>
  );
}

export default Home;
